
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Iddle
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:        http://www.iddleapp.com/  
#
# 2. URL of this page
url:              http://iddle.github.io/
#
# 3. About your kickstarter project
project: 
  #
  # Name of the project
  name:           Iddle
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:       http://bit.ly/1zAe2sv
  #
  # URL of a cover photo of your project
  cover_image:    http://i1381.photobucket.com/albums/ah239/iddleapp/trendingarrow_zps2b76f357.png
  #
  # Use a one-liner to describe your project
  description:    Iddle allows you to vote thumbs up or thumbs down on trending topics. Voting is anonymous.
#
# 4. Your Twitter handle
twitter_handle: IddleApp  
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  This is the Iddle team greeting you from Wilmington, NC. <br />
  First of all, thank you for your interest! <br />
  We're here to tell you that Iddle is now available on the App Store,
  and now we have to count on your support to not only download Iddle, but also share the love. ♥
